#!/bin/zsh
PROJECT="/Users/clarksonwthornburgh/Desktop/Whinfell_BUILD_Cousins"
LOG="$HOME/Desktop/whinfell_launcher.log"
cd "$PROJECT" || exit 1
{
  echo ""
  echo "=== EOD app launch $(date) ==="
  /usr/bin/python3 -c "import tkinter" 2>&1 || exit 2
  exec /usr/bin/python3 Whinfell_Daily_Launcher.py --eod
} >>"$LOG" 2>&1
CODE=$?
if [[ $CODE -ne 0 ]]; then
  /usr/bin/osascript -e "display alert \"Whinfell EOD failed (exit $CODE)\" message \"See Desktop/whinfell_launcher.log\""
fi
exit $CODE